version: '3.8'
 
services:
  meeting:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8000"
    networks:
      - web_nw
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - DATABASE_NAME=meeting
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=Msj.116159
      - HOST=postgres
      - PORT=5432
      - DEBUG=False
      - SECRET_KEY=django-insecure-)5cl@k5dt7*e8)%1i(6m&8a-g5et7!#oer=gu1qh6^0t($qjy#
    networks:
      - web_nw
 
networks:
  web_nw:
    driver: bridge

volumes:
  postgres: