# Generated by Django 4.0.4 on 2022-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceeding',
            name='participants_no',
        ),
        migrations.AddField(
            model_name='proceeding',
            name='participants',
            field=models.ManyToManyField(to='meeting.employee'),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='proceeding_no',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceeding',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
