# Generated by Django 4.0.4 on 2023-01-13 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_resolution_stockholder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceeding',
            name='ptime',
            field=models.TimeField(default=datetime.datetime(2023, 1, 13, 15, 26, 12, 153445, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceeding',
            name='upload',
            field=models.FileField(default=datetime.datetime(2023, 1, 13, 15, 26, 57, 784036, tzinfo=utc), upload_to='proceedings/'),
            preserve_default=False,
        ),
    ]
