# Generated by Django 4.0.4 on 2023-01-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_proceeding_ptime_proceeding_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceeding',
            name='ptime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='proceedings/'),
        ),
    ]
