# Generated by Django 4.0.4 on 2023-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_alter_proceeding_ptime_alter_proceeding_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceeding',
            name='upload',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
